### PR TITLE
Fix sphinx warnings

### LINKED ISSUE #299: Warnings when building docs
There are a few minor warnings when building the docs, such as 

```
/Users/tom/Documents/Work/Code/virtualizarr/docs/faq.md:58: WARNING: 'myst' cross-reference target not found: 'how-do-virtualizarr-and-kerchunk-compare' [myst.xref_missing]
/Users/tom/Documents/Work/Code/virtualizarr/docs/index.md:67: WARNING: more than one target found for 'myst' cross-reference usage: could be :std:ref:`Usage docs page` or :std:doc:`Usage docs page` [myst.xref_ambiguous]
/Users/tom/Documents/Work/Code/virtualizarr/docs/usage.md:73: WARNING: 'myst' cross-reference target not found: 'combining-virtual-datasets' [myst.xref_missing]
/Users/tom/Documents/Work/Code/virtualizarr/docs/usage.md:73: WARNING: 'myst' cross-reference target not found: 'writing-virtual-stores-to-disk' [myst.xref_missing]
```

It would be good to fix these and then change the readthedocs settings to count a warning as a failure, so that no broken links creep in again.

### PR DESCRIPTION
**Pull request by maxrjones**
This PR auto generates section references and updates the readthedocs CI to not fail on warnings

Closes #299

### CODE REVIEW

**Review by TomNicholas — COMMENTED** [review]
Thanks!

I actually want the docs CI to fail on warnings though - that way we catch them and can make sure nothing is wrong with the released docs whatsoever.

**Comment by maxrjones** [comment]
> I actually want the docs CI to fail on warnings though - that way we catch them and can make sure nothing is wrong with the released docs whatsoever.

Oh sorry! that's what I get for skim reading your original issue. I'll change it to fail on warnings.

**Comment by maxrjones** [comment]
Good call on the fail on warnings @TomNicholas, that prompted a few more fixes

**Review by TomNicholas — APPROVED** [review]
Thank you @maxrjones !

**Pull request merged**
