### PR TITLE
Add status badges to README

### LINKED ISSUE #302: Add some cool badges to the Readme
I would like some cool badges in our readme, like [these ones](https://github.com/pydata/xarray?tab=readme-ov-file#xarray-n-d-labeled-arrays-and-datasets)

### PR DESCRIPTION
**Pull request by douglatornell**
Inserted various status badges for CI, code coverage, documentation, linting, type checking, license, Python versions, latest release, and package downloads. These badges provide quick visual indicators of the project's current state and integrations.

- [x] Closes #302

### CODE REVIEW

**Comment by douglatornell** [comment]
Similarities and differences from the collection of badges in the xarray README:
* CI status - similar with appropriate URL changes
* codecov - similar with appropriate URL changes
* docs build status - similar with appropriate URL changes
* benchmarked by asv - excluded because it's not applicable
* code style black - replaced with Ruff badge because that what's used for linting & formatting
* mypy checked - similar with appropriate URL changes
* added pre-commit enabled badge because VirtualiZarr uses pre-commit and pre-commit.ci
* added Apache 2.0 license badge
* added supported Python version badge - gets Python version from `requires-python` item in `pyproject.toml` file
* replaced PyPI release badge id with one that gets release id from GitHub because that's where the releases are created
* PyPI downloads  - similar with appropriate URL changes
* conda downloads - please see discussion below
* DOI - excluded because VirtualiZarr doesn't have one (yet?)
* binder - excluded because I don't know if it's applicable
* X - excluded because it's X and does VirtualiZarr have a social media presence?

**Comment by douglatornell** [comment]
I can't get the conda downloads badge to work nicely. As committed the badge says "downloads" instead of "conda|downloads". That's from:
https://anaconda.org/conda-forge/virtualizarr/badges/downloads.svg?label=conda%7Cdownloads
which is the URL that has to be used to get the number of downloads to show. Using a URL similar to that in the xarray README:
https://img.shields.io/conda/dn/anaconda/vitrualizarr?label=conda%7Cdownloads
results in "not found" for the number of downloads.

**Comment by TomNicholas** [comment]
Awesome, thank you @douglatornell !

> DOI - excluded because VirtualiZarr doesn't have one (yet?)

Oh good point. I think we could just make one? Raised #305 to track this idea.

> X - excluded because it's X and does VirtualiZarr have a social media presence?

VirtualiZarr has nothing specific, but we could link to the `@zarr-developers` handle. But also X sucks so let's hold off on that.

> I can't get the conda downloads badge to work as I would like. As committed the badge says "downloads" instead of "conda|downloads". That's from:
`https://anaconda.org/conda-forge/virtualizarr/badges/downloads.svg?label=conda%7Cdownloads`

The xarray badge seems a little different - I think it might refer to the number of downloads from the anaconda distribution itself, not just conda-forge. VirtualiZarr isn't in the anaconda distribution.

> `https://img.shields.io/conda/dn/anaconda/vitrualizarr?label=conda%7Cdownloads`
results in "not found" for the number of downloads.

There's a typo in the word "virtualizarr" in this link - could that be the issue?

**Comment by douglatornell** [comment]
It turns out that there's a conda downloads badge defined on shields.io. I just needed to look in the right place: https://shields.io/badges/conda-downloads

**Pull request merged**
