### PR TITLE
Fix mypy errors around numpy functions not being strictly type hinted

### PR DESCRIPTION
**Pull request by TomNicholas**
Hoping this fixes some of the typing errors @norlandrhagen flagged in #249

### CODE REVIEW

**Comment by TomNicholas** [comment]
No idea what's going on with the `hdf5` dependency in the docs build

**Comment by norlandrhagen** [comment]
> No idea what's going on with the `hdf5` dependency in the docs build

For building the docs, do we need all the deps in the `      - -e  "..[test]" ` [line](https://github.com/zarr-developers/VirtualiZarr/blob/47a5e8702e44f71bb355bcba0ff6214fe6d09d83/ci/doc.yml#L16C21-L16C23)?

**Comment by TomNicholas** [comment]
> For building the docs, do we need all the deps in the      - -e  "..[test]" [line](https://github.com/zarr-developers/VirtualiZarr/blob/47a5e8702e44f71bb355bcba0ff6214fe6d09d83/ci/doc.yml#L16C21-L16C23)?

The docs don't actually dynamically run any examples (see https://github.com/zarr-developers/VirtualiZarr/issues/83), so almost certainly we don't.

**Comment by TomNicholas** [comment]
This passes the new separate test so should be good to merge?

**Pull request merged**
